apiVersion: v1
kind: ConfigMap
metadata: 
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: 966392474288.dkr.ecr.us-east-1.amazonaws.com/catalogue
        imagePullPolicy: Always
        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: catalogue
        resources:
          requests:
            cpu: "128m"
            memory: "256Mi"
          limits:
            cpu: "256m"
            memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  type: ClusterIP
  selector:
    project: roboshop
    tier: backend
    component: catalogue
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 

