apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: redis
spec:
  clusterIP: None
  selector:
    project: roboshop
    tier: db
    component: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-ebs
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: redis
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: redis
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: redis
    spec:
      containers:
      - name: redis
        image: 966392474288.dkr.ecr.us-east-1.amazonaws.com/redis
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "128m"
            memory: "256Mi"
          limits:
            cpu: "256m"
            memory: "512Mi"
        volumeMounts:
        - name: redis
          mountPath: /data
  #PVC        
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: redis-ebs
      resources:
        requests:
          storage: 5Gi    

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: redis
spec:
  type: ClusterIP
  selector:
    project: roboshop
    tier: db
    component: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379     