apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  clusterIP: None
  selector:
    project: roboshop
    tier: db
    component: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-ebs
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mysql
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mysql
    spec:
      containers:
      - name: mysql
        image: 966392474288.dkr.ecr.us-east-1.amazonaws.com/mysql
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "256m"
            memory: "512Mi"
          limits:
            cpu: "400m"
            memory: "756Mi"
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  #PVC        
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: mysql-ebs
      resources:
        requests:
          storage: 5Gi    


---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  type: ClusterIP
  selector:
    project: roboshop
    tier: db
    component: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306