apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  clusterIP: None
  selector:
    project: roboshop
    tier: db
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-ebs
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  serviceName: mongodb-headless
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mongodb
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: 966392474288.dkr.ecr.us-east-1.amazonaws.com/mongodb
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "128m"
            memory: "256Mi"
          limits:
            cpu: "256m"
            memory: "512Mi"
        volumeMounts:
          - name: mongodb
            mountPath: /data/db
  #PVC        
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: mongodb-ebs
      resources:
        requests:
          storage: 5Gi    

---  

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  type: ClusterIP
  selector:
    project: roboshop
    tier: db
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017     